apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  type: LoadBalancer
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-entrypoint
data:
  entrypoint.sh: |
    #!/usr/bin/env bash

    set -e

    id="$(hostname -f | sed -n 's/zk-\([[:digit:]]\+\).zookeeper.\+/\1/p')"

    if [[ ! -f /home/zookeeper/cluster-data/zk/data/myid ]]; then
      echo "$((id + 1))" > /home/zookeeper/cluster-data/zk/data/myid
    fi

    zkServer.sh start-foreground
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  serviceName: zookeeper
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zk
          image: zookeeper:latest
          imagePullPolicy: Never
          env:
            - name: ZOO_LOG4J_PROP
              value: INFO,ROLLINGFILE,CONSOLE
          command:
            - bash
            - /home/zookeeper/scripts/entrypoint.sh
          volumeMounts:
            - name: zookeeper-conf
              mountPath: /home/zookeeper/zookeeper-current/conf/zoo.cfg
              subPath: zoo.cfg
            - name: zookeeper-data
              mountPath: /home/zookeeper/cluster-data/zk/data
            - name: zookeeper-entrypoint
              mountPath: /home/zookeeper/scripts
      volumes:
        - name: zookeeper-conf
          configMap:
            name: zk-conf
        - name: zookeeper-entrypoint
          configMap:
            name: zookeeper-entrypoint
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512M
