apiVersion: v1
kind: Service
metadata:
  name: datanode
  labels:
    app: datanode
spec:
  clusterIP: None
  selector:
    app: datanode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dn
spec:
  serviceName: datanode
  replicas: 3
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - name: dn
          image: hdfs:latest
          imagePullPolicy: Never
          env:
            - name: HADOOP_ROOT_LOGGER
              value: INFO,DRFA,console
          command:
            - hdfs
            - datanode
          volumeMounts:
            - name: hdfs-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hdfs-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: datanode-data
              mountPath: /data
      volumes:
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
  volumeClaimTemplates:
    - metadata:
        name: datanode-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512M
