apiVersion: v1
kind: Service
metadata:
  name: journalnode
  labels:
    app: journalnode
spec:
  clusterIP: None
  selector:
    app: journalnode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jn
spec:
  serviceName: journalnode
  replicas: 3
  selector:
    matchLabels:
      app: journalnode
  template:
    metadata:
      labels:
        app: journalnode
    spec:
      containers:
        - name: jn
          image: hdfs:latest
          imagePullPolicy: Never
          env:
            - name: HADOOP_ROOT_LOGGER
              value: INFO,DRFA,console
          command:
            - hdfs
            - journalnode
          volumeMounts:
            - name: hdfs-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hdfs-conf
              mountPath: /home/hadoop/hadoop-current/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: journalnode-data
              mountPath: /data
      volumes:
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
  volumeClaimTemplates:
    - metadata:
        name: journalnode-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512M
