apiVersion: v1
kind: Service
metadata:
  name: hmaster
  labels:
    app: hmaster
spec:
  clusterIP: None
  selector:
    app: hmaster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hm
spec:
  serviceName: hmaster
  replicas: 2
  selector:
    matchLabels:
      app: hmaster
  template:
    metadata:
      labels:
        app: hmaster
    spec:
      containers:
        - name: hm
          image: hbase:latest
          imagePullPolicy: Never
          env:
            - name: HBASE_ROOT_LOGGER
              value: INFO,DRFA,console
          command:
            - hbase
            - master
            - start
          volumeMounts:
            - name: hbase-conf
              mountPath: /home/hbase/hbase-current/conf/hbase-site.xml
              subPath: hbase-site.xml
            - name: hdfs-conf
              mountPath: /home/hbase/hbase-current/conf/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hdfs-conf
              mountPath: /home/hbase/hbase-current/conf/core-site.xml
              subPath: core-site.xml
      volumes:
        - name: hbase-conf
          configMap:
            name: hbase-conf
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
