apiVersion: v1
kind: Service
metadata:
  name: regionserver
  labels:
    app: regionserver
spec:
  clusterIP: None
  selector:
    app: regionserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rs
spec:
  serviceName: regionserver
  replicas: 3
  selector:
    matchLabels:
      app: regionserver
  template:
    metadata:
      labels:
        app: regionserver
    spec:
      containers:
        - name: rs
          image: hbase:latest
          imagePullPolicy: Never
          env:
            - name: HBASE_CONF_DIR
              value: /home/hbase/conf
            - name: HBASE_ROOT_LOGGER
              value: INFO,DRFA,console
          command:
            - hbase
            - regionserver
            - start
          volumeMounts:
            - name: hbase-conf
              mountPath: /home/hbase/conf/hbase-site.xml
              subPath: hbase-site.xml
            - name: hbase-conf
              mountPath: /home/hbase/conf/backup-masters
              subPath: backup-masters
            - name: hbase-conf
              mountPath: /home/hbase/conf/regionservers
              subPath: regionservers
            - name: hbase-conf
              mountPath: /home/hbase/conf/log4j2.properties
              subPath: log4j2.properties
            - name: hdfs-conf
              mountPath: /home/hbase/conf/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hdfs-conf
              mountPath: /home/hbase/conf/core-site.xml
              subPath: core-site.xml
      volumes:
        - name: hbase-conf
          configMap:
            name: hbase-conf
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
